project:
  type: website
  output-dir: _site

website:
  title: "MRMhub"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "INTEGRATOR ↗"
        href: https://slinghub.github.io/MRMhub/integrator/
      - text: "QUANT (R package) ↗"
        href: https://slinghub.github.io/MRMhub/quant/
    right:
      - icon: github
        href: https://github.com/SLINGhub/MRMhub
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
